ALTER TABLE usuarios
  ADD COLUMN rol ENUM('usuario', 'admin') NOT NULL DEFAULT 'usuario' AFTER password_hash;

ALTER TABLE categorias
  ADD COLUMN activo TINYINT(1) NOT NULL DEFAULT 1 AFTER nombre;

ALTER TABLE productos
  ADD COLUMN activo TINYINT(1) NOT NULL DEFAULT 1 AFTER stock;

CREATE TABLE IF NOT EXISTS carrusel (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  descripcion TEXT,
  imagen VARCHAR(500) NOT NULL,
  link VARCHAR(500),
  orden INT NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
